language = "C"
include_guard = "GEARBOX_H"
cpp_compat = true
documentation = true
style = "type"
no_includes = false
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]

[parse]
parse_deps = false

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
prefix_with_name = true

[export]
include = [
    "gearbox_last_error_message",
    "gearbox_string_free",
    "gearbox_version",
]
item_types = ["functions", "typedefs", "opaque"]
